# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Example-OC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example-OC

pod 'YTKNetwork', '~> 2.0.4'

  pod 'Masonry', '~> 1.1.0'
  pod 'AFNetworking', '~> 3.1.0'
  pod 'SDWebImage', '~> 4.4.7'
  pod 'MJRefresh', '~> 3.1.15.3'
  pod 'JXPagingView/Pager','1.1.8'
  pod 'JXCategoryView','1.5.5'
  pod 'LookinServer', :configurations => ['Debug']
end
